import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";

const arimo = Arimo({
  variable: "--font-arimo-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "West London - IELTS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}